/*
 * Copyright (C) 2017 diana - All Rights Reserved
 *
 * 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * Althering the content of this licence under any circumstances is
 * strictly forbidden.
 * This application is part of a project developed during ERASMUS+ mobility
 * at University of Zaragoza, Spain.
 * This application is open-source and is distributed WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. 
 * 
 */
package operationplanning.ES;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import operationplanning.commonFiles.Users;
import operationplanning.commonFiles.Utils;

/**
 *
 * @author diana
 */
public class CurrentUserPanel_ES extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel_EN
     * @param userType
     */
    public CurrentUserPanel_ES() {

        initComponents();
        
        userNameTextField.setText(Planning_ES.currentUserName);
        if (Planning_ES.currentUserType != Utils.UserType.HEAD_OF_DEPARTMENT) {
            userNameTextField.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        newPasswordField = new javax.swing.JPasswordField();
        repeatPasswordField = new javax.swing.JPasswordField();
        newPasswordLabel = new javax.swing.JLabel();
        repeatPasswordLabel = new javax.swing.JLabel();
        resetPasswordButton = new javax.swing.JButton();
        currentPasswordField = new javax.swing.JPasswordField();
        currentPasswordLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        userNameLabel.setText("User name");

        newPasswordLabel.setText("Nueva contraseña");

        repeatPasswordLabel.setText("Repite la contraseña");

        resetPasswordButton.setText("Cambia la contraseña");
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });

        currentPasswordLabel.setText("Contraseña actual (*)");

        jLabel1.setText("(*) Obligatorio sólo para el usuario actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currentPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(repeatPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(repeatPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                    .addComponent(newPasswordField)
                                    .addComponent(currentPasswordField)
                                    .addComponent(userNameTextField))
                                .addGap(240, 240, 240))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentPasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeatPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resetPasswordButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        Users userInst = Users.getInstance();
        String currentPassword = String.copyValueOf(currentPasswordField.getPassword());
        String newPassword = String.copyValueOf(newPasswordField.getPassword());
        String repeatPassword = String.copyValueOf(repeatPasswordField.getPassword());

        if("".equals(userNameTextField.getText())
                || "".equals(newPassword) || "".equals(repeatPassword)) {
            JOptionPane.showConfirmDialog(null, "Uno o más campos están vacíos."
                    + "\nCambio de contraseña anulada.", "Error. Campos vacíos", JOptionPane.DEFAULT_OPTION);
            return;
        }
        if(userNameTextField.getText().equals(Planning_ES.currentUserName) &&
                "".equals(currentPassword)) {
            JOptionPane.showConfirmDialog(null, "Uno o más campos están vacíos."
                    + "\nCambio de contraseña anulada.", "Error. Campos vacíos", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        if (!userInst.checkUserCredentials(userNameTextField.getText(), currentPassword)) {
            JOptionPane.showConfirmDialog(null, "El nombre de usuario y la contraseña actual no coinciden."
                    + "\nCambio de contraseña anulada.", "Error de coincidencia de nombre de usuario y contraseña", JOptionPane.DEFAULT_OPTION);
            return;
        }
        if (!newPassword.equals(repeatPassword)) {
            JOptionPane.showConfirmDialog(null, "La nueva contraseña no es la misma en ambos campos."
                    + "\nCambio de contraseña anulada.", "La contraseña no coincide", JOptionPane.DEFAULT_OPTION);
            return;
        }

        int ans = JOptionPane.showOptionDialog(null, new JLabel("<html>¿Está seguro de que desea cambiar la contraseña\n"
                + " para el usuario <b>" + userNameTextField.getText() + "</b>?</html>"),
                "Cambiar la confirmación de contraseña",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, null, JOptionPane.OK_OPTION);
        if (ans == JOptionPane.OK_OPTION) {
            userInst.changePasswordForUser(userNameTextField.getText(), newPassword);
            JOptionPane.showConfirmDialog(null, "La contraseña se ha cambiado correctamente.",
                    "Contraseña cambiada con éxito",
                    JOptionPane.DEFAULT_OPTION);
            currentPasswordField.setText("");
            newPasswordField.setText("");
            repeatPasswordField.setText("");
        }
    }//GEN-LAST:event_resetPasswordButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField currentPasswordField;
    private javax.swing.JLabel currentPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField repeatPasswordField;
    private javax.swing.JLabel repeatPasswordLabel;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
