/*
 * Copyright (C) 2017 Diana Botez <dia.botez at gmail.com> - All Rights Reserved
 *
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * Althering the content of this licence under any circumstances is
 * strictly forbidden.
 * This application is part of a project developed during ERASMUS+ mobility
 * at University of Zaragoza, Spain.
 * This application is open-source and is distributed WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.
 *
 */
package operationplanning.EN;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import operationplanning.commonFiles.DatabaseQueries;
import operationplanning.commonFiles.MedicIdentifiers;
import operationplanning.commonFiles.MedicalTeams;
import operationplanning.commonFiles.OperationRooms;
import operationplanning.commonFiles.PatientIdentifiers;
import operationplanning.commonFiles.PatientsList;
import operationplanning.commonFiles.Utils;
import operationplanning.cplex.files.Opep;

/**
 * @abstract
 *
 * @author Diana Botez
 */
public class CreateSchedulePanel_EN extends JPanel {

    private static MedicalTeams medicalInst = new MedicalTeams();

    /**
     * Creates new form CrateSchedulePanel
     */
    public CreateSchedulePanel_EN() {
        initComponents();

        updateMedicList();

        if (Planning_EN.currentUserType != Utils.UserType.HEAD_OF_DEPARTMENT) {
            generateAverageOccupancyRateButton.setEnabled(false);
            minimumConfidenceLevelFormattedTextField.setEnabled(false);
            minimumConfidenceLevelLabel.setEnabled(false);
        }
    }

    public static void updateMedicList() {
        if (medicComboBox == null) {
            return;
        }

        medicComboBox.removeAllItems();

        Vector<Vector<String>> teamDetails = medicalInst.getAllTeamDetails();
        for (Vector<String> teamDetail : teamDetails) {
            MedicIdentifiers coordinator = medicalInst.getCoordinator(Integer.parseInt(teamDetail.get(0).replace("TM", "")));
            if (coordinator == null) {
                continue;
            }
            medicComboBox.addItem(teamDetail.get(1) + " ( " + coordinator.lastName + " " + coordinator.firstName + " )");
        }
        medicComboBox.setSelectedIndex(0);
        dayOccupancyPercentageFormattedTextField1.setValue(new OperationRooms().getAverageOccupancyRate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        dayDeviacionFormattedTextField2 = new javax.swing.JFormattedTextField();
        dayOccupancyPercentageFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numberOfDaysToScheduleFormattedTextField = new javax.swing.JFormattedTextField();
        medicComboBox = new javax.swing.JComboBox<>();
        generateAverageOccupancyRateButton = new javax.swing.JButton();
        minimumConfidenceLevelLabel = new javax.swing.JLabel();
        minimumConfidenceLevelFormattedTextField = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(640, 480));

        scheduleButton.setText("schedule patients");
        scheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleButtonActionPerformed(evt);
            }
        });

        resultTextArea.setEditable(false);
        resultTextArea.setColumns(20);
        resultTextArea.setLineWrap(true);
        resultTextArea.setRows(5);
        resultTextArea.setTabSize(4);
        jScrollPane2.setViewportView(resultTextArea);

        jLabel3.setText("Accepted deviation rate (percentage)");

        dayDeviacionFormattedTextField2.setText("15");

        dayOccupancyPercentageFormattedTextField1.setText("80");

        jLabel2.setText("Desired occupancy rate (percentage)");

        jLabel1.setText("Days to schedule (bigger or equal with 1)");

        numberOfDaysToScheduleFormattedTextField.setText("5");

        medicComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicComboBoxActionPerformed(evt);
            }
        });

        generateAverageOccupancyRateButton.setText("Generate average occupancy rate");
        generateAverageOccupancyRateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateAverageOccupancyRateButtonActionPerformed(evt);
            }
        });

        minimumConfidenceLevelLabel.setText("Minimum confidence level (51 - 99)");

        minimumConfidenceLevelFormattedTextField.setText("80");
        minimumConfidenceLevelFormattedTextField.setMinimumSize(new java.awt.Dimension(20, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scheduleButton)
                        .addGap(18, 18, 18)
                        .addComponent(medicComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minimumConfidenceLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dayOccupancyPercentageFormattedTextField1)
                            .addComponent(dayDeviacionFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(numberOfDaysToScheduleFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(minimumConfidenceLevelFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generateAverageOccupancyRateButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberOfDaysToScheduleFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateAverageOccupancyRateButton)
                    .addComponent(minimumConfidenceLevelFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimumConfidenceLevelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayOccupancyPercentageFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dayDeviacionFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scheduleButton)
                    .addComponent(medicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleButtonActionPerformed
        scheduleButton.setText("Loading...");
        scheduleButton.setEnabled(false);

        new Thread(new Runnable() {
            @Override
            public void run() {
                if (null == medicComboBox.getSelectedItem()) {
                    return;
                }

                String item = medicComboBox.getSelectedItem().toString();
                String teamName = item.substring(0, item.indexOf('(')).trim();
                String teamId = new DatabaseQueries().getTeamIdByTeamName(teamName);

                MedicIdentifiers doctor = medicalInst.getCoordinator(Integer.parseInt(teamId.replace("TM", "")));
                Vector<PatientIdentifiers> patients;
                PatientsList patientsInst = new PatientsList();

                if (doctor == null) {
                    JOptionPane.showConfirmDialog(null, "Doctor not found", "Unkbown doctor", JOptionPane.DEFAULT_OPTION);
                    return;
                } else {
                    patients = patientsInst.getDoctorOrTeamPatientList(doctor.IDnumber, true, false);
                }

                //set patient list
                Opep cplexObject = new Opep();
                cplexObject.setPatientList(patients);

                int availableDatesNo = new OperationRooms().getNumberOfOrAvailableDatesAssigned(teamId);
                int days = Integer.parseInt(numberOfDaysToScheduleFormattedTextField.getText());
                int dayPercentage = Integer.parseInt(dayOccupancyPercentageFormattedTextField1.getText());
                int dayDeviation = Integer.parseInt(dayDeviacionFormattedTextField2.getText());
                Vector<Vector<String>> availableDatesDetails = new DatabaseQueries().getAvailableDatesToScheduleForTeam(teamId);
                Vector<Vector<Integer>> scheduledPatients;

                if (availableDatesNo == 0) {
                    JOptionPane.showConfirmDialog(null, "No days available to schedule for the selected team.",
                            "Error. Cannot create schedule",
                            JOptionPane.DEFAULT_OPTION);
                } else if (days == 0) {
                    JOptionPane.showConfirmDialog(null, "Number of days to schedule has to be greater or equal with 1.",
                            "Error. Cannot create schedule",
                            JOptionPane.DEFAULT_OPTION);
                } else if (days > availableDatesNo) {
                    JOptionPane.showConfirmDialog(null, "Maximum number of available dates is " + availableDatesNo + ".",
                            "Error. Wrong number of dates to schedule",
                            JOptionPane.DEFAULT_OPTION);
                    numberOfDaysToScheduleFormattedTextField.setText("" + availableDatesNo);
                } else if (days <= availableDatesNo) {
                    scheduledPatients = cplexObject.opep_main(days, dayPercentage, dayDeviation, 1, teamId);//create a new schedule
                    String message;
                    if (scheduledPatients != null && !scheduledPatients.isEmpty()) {
                        int index = 0;
                        message = "Following patients have been scheduled: \n";
                        for (Vector<Integer> scheduledPatientsPerDay : scheduledPatients) {
                            message += availableDatesDetails.get(index).get(0) + " (";
                            message += availableDatesDetails.get(index).get(1) + "):\t";
                            for (Integer patientId : scheduledPatientsPerDay) {
                                message += patientId + "\t";
                            }
                            message += "\n";
                            index++;
                        }
                    } else {
                        message = "No patient has been scheduled\n";
                    }
                    resultTextArea.setText(message);
                }

                scheduleButton.setText("Schedule");
                scheduleButton.setEnabled(true);
            }
        }).start();

    }//GEN-LAST:event_scheduleButtonActionPerformed

    private void generateAverageOccupancyRateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateAverageOccupancyRateButtonActionPerformed
        int answer = JOptionPane.showOptionDialog(null, "This operation might take a while. "
                + "You can do other operations until it is done.\n\n"
                + "Are you sure you want to start computing the average?",
                "Computing average occupancy rate",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, JOptionPane.NO_OPTION);

        if (JOptionPane.YES_OPTION != answer) {
            return;
        }

        int confidenceLevel = Integer.parseInt(minimumConfidenceLevelFormattedTextField.getText());
        if (confidenceLevel < 51) {
            JOptionPane.showConfirmDialog(null,
                    "Minimum confidence level is too low.",
                    "Error. Minimum confidence level",
                    JOptionPane.DEFAULT_OPTION);
            return;
        }

        //ask for confidence level
        generateAverageOccupancyRateButton.setText("Computing...");
        generateAverageOccupancyRateButton.setEnabled(false);

        new Thread(new Runnable() {
            @Override
            public void run() {
                PatientsList patientsInst = new PatientsList();
                Vector<PatientIdentifiers> patients = patientsInst.getDoctorOrTeamPatientList(-1, false, false);

                //set patient list
                Opep cplexObject = new Opep();
                cplexObject.setPatientList(patients);

                double averageOccupancyRate;
                averageOccupancyRate = cplexObject.opep_generateOccupancyRate(confidenceLevel);//create a new schedule

                if (0 != averageOccupancyRate) {
                    dayOccupancyPercentageFormattedTextField1.setValue((int) averageOccupancyRate);
                    new OperationRooms().setAverageOccupancyRate((int) averageOccupancyRate);

                    Object[] obj = {"OK"};
                    JOptionPane.showOptionDialog(null, "The average occupancy rate was generated. "
                            + "You can find it in \"Desired occupancy rate\" filed.",
                            "Average occupancy rate computed",
                            JOptionPane.OK_OPTION,
                            JOptionPane.INFORMATION_MESSAGE,
                            null, obj, JOptionPane.OK_OPTION);
                } else {
                    JOptionPane.showConfirmDialog(null,
                            "The average occupancy rate could not be generated.",
                            "Error. Generating average occupancy rate",
                            JOptionPane.DEFAULT_OPTION);
                }

                generateAverageOccupancyRateButton.setText("Generate average occupancy rate");
                generateAverageOccupancyRateButton.setEnabled(true);
            }
        }).start();
    }//GEN-LAST:event_generateAverageOccupancyRateButtonActionPerformed

    private void medicComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicComboBoxActionPerformed
        if (medicComboBox == null || medicComboBox.getSelectedIndex() == -1) {
            return;
        }

        String item = medicComboBox.getSelectedItem().toString();
        String teamName = item.substring(0, item.indexOf('(')).trim();
        String teamId = new DatabaseQueries().getTeamIdByTeamName(teamName);

        int availableDatesNo = new OperationRooms().getNumberOfOrAvailableDatesAssigned(teamId);

        numberOfDaysToScheduleFormattedTextField.setValue(availableDatesNo);
    }//GEN-LAST:event_medicComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dayDeviacionFormattedTextField2;
    private static javax.swing.JFormattedTextField dayOccupancyPercentageFormattedTextField1;
    private javax.swing.JButton generateAverageOccupancyRateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JComboBox<String> medicComboBox;
    private static javax.swing.JFormattedTextField minimumConfidenceLevelFormattedTextField;
    private javax.swing.JLabel minimumConfidenceLevelLabel;
    private javax.swing.JFormattedTextField numberOfDaysToScheduleFormattedTextField;
    public static javax.swing.JTextArea resultTextArea;
    private javax.swing.JButton scheduleButton;
    // End of variables declaration//GEN-END:variables
}
