/*
 * Copyright (C) 2017 Diana Botez <dia.botez at gmail.com> - All Rights Reserved
 *
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * Althering the content of this licence under any circumstances is
 * strictly forbidden.
 * This application is part of a project developed during ERASMUS+ mobility
 * at University of Zaragoza, Spain.
 * This application is open-source and is distributed WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.
 *
 */
package operationplanning.EN;

import operationplanning.commonFiles.SurgeriesList;
import java.util.Vector;
import javax.swing.JOptionPane;
import operationplanning.commonFiles.DatabaseQueries;

/**
 *
 * @author Diana Botez <dia.botez at gmail.com>
 */
public class UpdateRemoveSurgeryWindow_EN extends javax.swing.JFrame {

    Vector<Vector<String>> surgeriesDetails;

    /**
     * Creates new form UpdateRemovePathology
     */
    public UpdateRemoveSurgeryWindow_EN() {
        initComponents();
        surgeriesDetails = new DatabaseQueries().getAllSurgeriesDetails();

        for (Vector<String> surgeriesDetail : surgeriesDetails) {
            surgeryComboBox.addItem(surgeriesDetail.get(0));
        }
        surgeryComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pathologyLabel = new javax.swing.JLabel();
        surgeryLabel = new javax.swing.JLabel();
        pathologyTextField = new javax.swing.JTextField();
        avgDurationLabel = new javax.swing.JLabel();
        avgDurationFormattedTextField = new javax.swing.JFormattedTextField();
        stdDeviationLabel = new javax.swing.JLabel();
        stdDeviationFormattedTextField = new javax.swing.JFormattedTextField();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        surgeryComboBox = new javax.swing.JComboBox<>();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pathologyLabel.setText("Pathology");

        surgeryLabel.setText("Surgery");

        avgDurationLabel.setText("Average duration (min)");

        avgDurationFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));

        stdDeviationLabel.setText("Standard deviation (min)");

        stdDeviationFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        surgeryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeryComboBoxActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(surgeryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdDeviationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathologyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avgDurationFormattedTextField)
                    .addComponent(stdDeviationFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pathologyTextField)
                    .addComponent(surgeryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surgeryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surgeryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathologyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathologyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgDurationFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdDeviationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdDeviationFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(cancelButton)
                    .addComponent(removeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (surgeryComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No surgery to update. Please select one.\n",
                    "Error ",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String srg = surgeryComboBox.getSelectedItem().toString();
        String ptg = pathologyTextField.getText();
        String avg = avgDurationFormattedTextField.getText();
        String std = stdDeviationFormattedTextField.getText();

        if ("".equals(srg) || "".equals(ptg) || "".equals(avg) || "".equals(std)) {
            JOptionPane.showMessageDialog(this, "One ore more fields are not completed.\n", "Error ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Object[] o = {"Update", "Cancel"};

        int option = JOptionPane.showOptionDialog(this, "The datas you introduced are:\n"
                + "\nsurgery - " + srg
                + "\npathology - " + ptg
                + "\navrage duration - " + avg
                + "\nstandard deviation - " + std
                + "\n\n Are you sure you want to update the old data with these ones?",
                "Check info",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, o, o[0]);

        if (option == 0) {
            //update the data
            SurgeriesListPanel_EN.updateSurgeryEntry(srg, ptg, avg, std);
            this.dispose();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (surgeryComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No surgery to remove.\n",
                    "Error ",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String srg = surgeryComboBox.getSelectedItem().toString();

        Object[] o = {"Remove", "Cancel"};

        int option = JOptionPane.showOptionDialog(this, "You are about to delete the following surgery:\n"
                + srg
                + "\n\n Are you sure you want to remove it data permanently form the database?",
                "Warning! Data removing",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE, null, o, o[1]);

        if (option == 0) {
            //remove data
            if (!SurgeriesListPanel_EN.removeSurgeryEntry(srg)) {
                JOptionPane.showConfirmDialog(null,
                        "Surgery could not be deleted. \n"
                        + "There might be patients that are scheduled or need to be \n"
                        + "scheduled for this surgery.",
                        "Error deleting surgery",
                        JOptionPane.DEFAULT_OPTION);
            }
            this.dispose();
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void surgeryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeryComboBoxActionPerformed
        if (surgeryComboBox.getSelectedItem() == null) {
            pathologyTextField.setText("");
            avgDurationFormattedTextField.setText("");
            stdDeviationFormattedTextField.setText("");
            return;
        }

        int selectedSurgeryIndex = surgeryComboBox.getSelectedIndex();
        if (selectedSurgeryIndex == -1) {
            //nothing selected. Make sure everything is empty
            pathologyTextField.setText("");
            avgDurationFormattedTextField.setText("");
            stdDeviationFormattedTextField.setText("");
            return;
        }

        //update fields
        pathologyTextField.setText(surgeriesDetails.get(selectedSurgeryIndex).get(1));
        avgDurationFormattedTextField.setText(surgeriesDetails.get(selectedSurgeryIndex).get(2));
        stdDeviationFormattedTextField.setText(surgeriesDetails.get(selectedSurgeryIndex).get(3));
    }//GEN-LAST:event_surgeryComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField avgDurationFormattedTextField;
    private javax.swing.JLabel avgDurationLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pathologyLabel;
    private javax.swing.JTextField pathologyTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JFormattedTextField stdDeviationFormattedTextField;
    private javax.swing.JLabel stdDeviationLabel;
    private javax.swing.JComboBox<String> surgeryComboBox;
    private javax.swing.JLabel surgeryLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
