/*
 * Copyright (C) 2017 diana - All Rights Reserved
 *
 * 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * Althering the content of this licence under any circumstances is
 * strictly forbidden.
 * This application is part of a project developed during ERASMUS+ mobility
 * at University of Zaragoza, Spain.
 * This application is open-source and is distributed WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. 
 * 
 */
package operationplanning.mainFiles;

import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author diana
 */
public class WelcomeWindow extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeWindow
     */
    public WelcomeWindow() {
        BufferedImage myPicture = null;
        try {
            myPicture = ImageIO.read(this.getClass().getResource("/images/Logo.jpg"));
            setIconImage(myPicture);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
//        if (myPicture != null) {
//            setContentPane(new JLabel(new ImageIcon(myPicture)));
//        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        logIn_ES_Button = new javax.swing.JButton();
        logIn_EN_Button = new javax.swing.JButton();
        creditsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome! Bienvenido!");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(500, 220));
        setMinimumSize(new java.awt.Dimension(500, 220));
        setPreferredSize(new java.awt.Dimension(500, 220));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 220));

        logIn_ES_Button.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        logIn_ES_Button.setText(" Iniciar sesión");
        logIn_ES_Button.setBorder(null);
        logIn_ES_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logIn_ES_ButtonActionPerformed(evt);
            }
        });

        logIn_EN_Button.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        logIn_EN_Button.setText("Login");
        logIn_EN_Button.setBorder(null);
        logIn_EN_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logIn_EN_ButtonActionPerformed(evt);
            }
        });

        creditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        creditsLabel.setText("<html>Application development and design, "
            + "Database structure and schema design: <i><b>Diana Botez</b></i> | "
            + "Scheduling algoritms: <i>Daniel Clavel Villagrasa</i> | "
            + "Instructor: <i>Cristian Mahulea</i> | "
            + "University: <i>Universidad de Zaragoza</i>"
            + "<br>Version: 0.1 (Beta)</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(logIn_EN_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(logIn_ES_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creditsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logIn_EN_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logIn_ES_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logIn_EN_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logIn_EN_ButtonActionPerformed
        LogInForm_EN_ES window = new LogInForm_EN_ES("EN", this);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logIn_EN_ButtonActionPerformed

    private void logIn_ES_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logIn_ES_ButtonActionPerformed
        LogInForm_EN_ES window = new LogInForm_EN_ES("ES", this);
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logIn_ES_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton logIn_EN_Button;
    private javax.swing.JButton logIn_ES_Button;
    // End of variables declaration//GEN-END:variables
}
